<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-R5SC2BLC" failures="1" tests="3" name="AddToCartTest" time="18.418" errors="0" timestamp="2025-02-18T13:36:42 IST">
  <testcase classname="com.automation.tests.LoginTest" name="verifyInvalidLogin" time="2.145">
    <failure type="java.lang.AssertionError" message="Error Msg is Not Matched ...  expected [Epic sadface  Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: Error Msg is Not Matched ...  expected [Epic sadface  Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]
at com.automation.tests.LoginTest.verifyInvalidLogin(LoginTest.java:55)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- verifyInvalidLogin -->
  <testcase classname="com.automation.tests.LoginTest" name="verifyValidLogin" time="3.988"/>
  <testcase classname="com.automation.tests.LoginTest" name="verifyInvalidLoginByDataDriven" time="10.159"/>
</testsuite> <!-- AddToCartTest -->
